import "~/styles/globals.css";
import { cn } from "../lib/utils";
import Navbar  from "./_components/Navbar";
import { type Metadata } from "next";
import { Geist } from "next/font/google";
import { Inter } from "next/font/google";
import { TRPCReactProvider } from "~/trpc/react";
import { ClerkProvider } from "@clerk/nextjs";
import { ClerkProvider } from "@clerk/nextjs";
import { NextSSRPlugin } from "@uploadthing/react/next-ssr-plugin";
import { extractRouterConfig } from "uploadthing/server";
import { ourFileRouter } from "~/app/api/uploadthing/core";

export const metadata: Metadata = {
  title: "ThriftiNUS",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/ThriftiNUS.svg" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${geist.variable}`}>
      <body
        className={cn("antialised relative h-full font-sans", inter.className)}
      >
        <ClerkProvider>
          <TRPCReactProvider>
            <main className="relative flex min-h-screen flex-col">
              {/* <Providers> */}
                <Navbar />
                <div className="flex-1 flex-grow">{children}</div>
                {/* <Footer />
              </Providers> */}
            </main>
          </TRPCReactProvider>
        </ClerkProvider>
        <NextSSRPlugin
          routerConfig={extractRouterConfig(ourFileRouter)}
        />
      </body>
    </html>
  );
}
